In [0]:
pip install faker

Collecting faker
  Downloading faker-40.31.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.31.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 12.2 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.31.0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
from faker import Faker
from datetime import datetime
import pandas as pd
import random

In [0]:
fake=Faker()
random.seed(42)
Faker.seed(42)

In [0]:
NUM_CUSTOMERS = 800
NUM_PRODUCTS = 700
NUM_ORDERS = 900
NUM_ORDER_ITEMS = 2000

CUSTOMER_TYPES = [
    "REGULAR",
    "PREMIUM",
    "VIP"
]

CATEGORIES = [
    "Electronics",
    "Clothing",
    "Home",
    "Books"
]

ORDER_STATUS = [
    "PLACED",
    "SHIPPED",
    "DELIVERED",
    "CANCELLED",
    "RETURNED"
]

In [0]:
def generate_customers(num_customers):
    customers = []
    cities = [
        "Hyderabad",
        "Bangalore",
        "Chennai",
        "Mumbai",
        "Delhi",
        "Pune",
        "Kolkata",
        "Ahmedabad"
    ]
    for customer_id in range(1, num_customers + 1):
        customer = {}
        customer["customer_id"] = customer_id
        customer["customer_name"] = fake.name()
        email = fake.email()
        # Creating invaid emails around 2%
        if random.random() < 0.02:
            if random.choice([True, False]):
                email = email.replace("@", "")
            else:
                email = email.split("@")[0]

        customer["email"] = email
        customer["city"] = random.choice(cities)
        customer["customer_type"] = random.choice(CUSTOMER_TYPES)
        customers.append(customer)
    return pd.DataFrame(customers)

In [0]:
customers_df = generate_customers(NUM_CUSTOMERS)
customers_df.head()

   customer_id    customer_name  ...       city customer_type
0            1     Allison Hill  ...    Kolkata       REGULAR
1            2  Angie Henderson  ...     Mumbai       REGULAR
2            3  Cristian Santos  ...  Hyderabad           VIP
3            4  Abigail Shaffer  ...    Kolkata       REGULAR
4            5  Gabrielle Davis  ...      Delhi       REGULAR

[5 rows x 5 columns]

In [0]:
customers_df.shape

(800, 5)

In [0]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    800 non-null    int64
 1   customer_name  800 non-null    object
 2   email          800 non-null    object
 3   city           800 non-null    object
 4   customer_type  800 non-null    object
dtypes: int64(1), object(4)
memory usage: 31.4+ KB

In [0]:

PRODUCTS = {
    "Electronics": [
        "iPhone 15",
        "Samsung Galaxy S24",
        "Dell Laptop",
        "HP Laptop",
        "Sony Headphones",
        "Bluetooth Speaker",
        "Smart Watch",
        "Wireless Mouse",
        "Mechanical Keyboard",
        "Power Bank",
        "USB Cable",
        "Monitor",
        "Webcam",
        "Gaming Mouse",
        "Printer"
    ],

    "Clothing": [
        "T-Shirt",
        "Jeans",
        "Hoodie",
        "Jacket",
        "Sneakers",
        "Formal Shirt",
        "Kurta",
        "Track Pants",
        "Cap",
        "Socks",
        "Sweatshirt",
        "Polo Shirt"
    ],

    "Home": [
        "Dining Table",
        "Sofa",
        "Wall Clock",
        "Microwave",
        "Mixer Grinder",
        "Vacuum Cleaner",
        "Water Bottle",
        "Chair",
        "Study Table",
        "Curtains",
        "LED Lamp",
        "Pressure Cooker"
    ],

    "Books": [
        "Python Programming",
        "SQL Cookbook",
        "Machine Learning Basics",
        "Data Engineering Guide",
        "Clean Code",
        "Atomic Habits",
        "Deep Learning",
        "Operating Systems",
        "Computer Networks",
        "DSA Handbook"
    ]
}

In [0]:
def generate_products(num_products):
    products = []
    for product_id in range(1, num_products + 1):
        #coosing a random category
        category = random.choice(CATEGORIES)
        product_name = random.choice(PRODUCTS[category])
        probability = random.random()
        # 5% of dirty data with extra spaces
        if probability < 0.05:
            product_name = "   " + product_name + "   "
        # 5% of dirty data with upper/lower case
        elif probability < 0.10:
            product_name = product_name.swapcase()
        #generating random nums between 100-5000
        price = round(random.uniform(100, 50000), 2)
        products.append({
            "product_id": product_id,
            "product_name": product_name,
            "category": category,
            "unit_price": price
        })

    return pd.DataFrame(products)

In [0]:
products_df = generate_products(NUM_PRODUCTS)
products_df.head()

   product_id        product_name     category  unit_price
0           1              Jacket     Clothing     6396.68
1           2        SQL Cookbook        Books    21826.12
2           3               Socks     Clothing    45549.14
3           4  Samsung Galaxy S24  Electronics    19928.01
4           5       Mixer Grinder         Home    45866.38

In [0]:
#random 15 rows 
products_df.sample(15)

     product_id              product_name     category  unit_price
573         574              SQL Cookbook        Books    23199.13
342         343         Operating Systems        Books    38316.87
131         132                Polo Shirt     Clothing    36551.68
268         269                    Webcam  Electronics    32050.54
635         636                     Socks     Clothing    35432.95
78           79                    Jacket     Clothing    31552.54
421         422            Vacuum Cleaner         Home    21771.79
51           52             Atomic Habits        Books    29319.98
43           44                Clean Code        Books    20986.43
84           85           Pressure Cooker         Home     8102.64
397         398                      Sofa         Home    48033.28
663         664     Python Programming           Books     2897.12
375         376    Data Engineering Guide        Books    27961.69
66           67                     Jeans     Clothing    29474.67
308         309                 Microwave         Home    42829.81

In [0]:
products_df.shape

(700, 4)

In [0]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    700 non-null    int64
 1   product_name  700 non-null    object
 2   category      700 non-null    object
 3   unit_price    700 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 22.0+ KB

In [0]:
def generate_orders(num_orders, num_customers):
    orders = []
    for order_id in range(1, num_orders + 1):
        #5% null customer id
        if random.random() < 0.05:
            customer_id = None
        else:
            customer_id = random.randint(1, num_customers)
        #date
        order_date = fake.date_time_between(
            start_date="-2y",
            end_date="now"
        )
        # 5% Wrong Date Format
        if random.random() < 0.05:
            order_date = order_date.strftime("%d-%m-%Y %H:%M:%S")
        else:
            order_date = order_date.strftime("%Y-%m-%d %H:%M:%S")
        status = random.choice(ORDER_STATUS)
        orders.append({
            "order_id": order_id,
            "customer_id": customer_id,
            "order_date": order_date,
            "status": status
        })

    return pd.DataFrame(orders)

In [0]:
orders_df = generate_orders(NUM_ORDERS, NUM_CUSTOMERS)
orders_df.head()

   order_id  customer_id           order_date     status
0         1        711.0  2025-01-26 00:16:36    SHIPPED
1         2        215.0  2025-08-09 15:30:55     PLACED
2         3        782.0  2025-05-31 17:36:43     PLACED
3         4          NaN  2025-02-14 03:01:30  CANCELLED
4         5          NaN  2026-02-20 14:05:53   RETURNED

In [0]:
orders_df.shape

(900, 4)

In [0]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     900 non-null    int64
 1   customer_id  853 non-null    float64
 2   order_date   900 non-null    object
 3   status       900 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 28.3+ KB

In [0]:
orders_df["customer_id"].isna().sum()

np.int64(47)

In [0]:
orders_df["status"].value_counts()

status
CANCELLED    194
SHIPPED      185
DELIVERED    177
PLACED       174
RETURNED     170
Name: count, dtype: int64

In [0]:
def generate_order_items(orders_df, num_products):
    order_items = []
    order_item_id = 1
    for order_id in orders_df["order_id"]:
        # Every order has 1 to 5 products
        number_of_products = random.randint(1, 5)
        # Prevent duplicate product in same order
        selected_products = random.sample(
            range(1, num_products + 1),
            number_of_products
        )
        for product_id in selected_products:
            quantity = random.randint(1, 5)
            # 3% Negative Quantity
            if random.random() < 0.03:
                quantity *= -1
            discount = round(random.uniform(0, 100), 2)
            order_items.append({
                "order_item_id": order_item_id,
                "order_id": order_id,
                "product_id": product_id,
                "quantity": quantity,
                "discount_percent": discount
            })
            order_item_id += 1
    return pd.DataFrame(order_items)

In [0]:
order_items_df = generate_order_items(orders_df,NUM_PRODUCTS)
order_items_df.head()

   order_item_id  order_id  product_id  quantity  discount_percent
0              1         1         581         3             52.53
1              2         2         151         1             73.62
2              3         2          97         4             35.08
3              4         3         264        -4             35.26
4              5         3         680         3             77.45

In [0]:
order_items_df.shape

(2637, 5)

In [0]:
(order_items_df["quantity"] < 0).sum()

np.int64(70)

In [0]:
%sql
create catalog Mini_Project;

In [0]:
%sql
create volume mini_project.default.Raw_Data;

In [0]:
customers_df.to_csv("/Volumes/mini_project/default/raw_data/customers.csv", index=False)
products_df.to_csv("/Volumes/mini_project/default/raw_data/products.csv", index=False)
orders_df.to_csv("/Volumes/mini_project/default/raw_data/orders.csv", index=False)
order_items_df.to_csv("/Volumes/mini_project/default/raw_data/order_items.csv", index=False)
print("All CSV files saved successfully!")

All CSV files saved successfully!